stages:
  - build
  - test
  - deploy
build:
  image: golang:1.12.1
  stage: build
  script:
    - export GO111MODULE=on 
    - ln -s $PWD $GOPATH/src/gua
    - cd $GOPATH/src/gua
    - make build/linux
build:linux:
  image: golang:1.12.1
  stage: build
  script:
    - export GO111MODULE=on
    - ln -s $PWD $GOPATH/src/gua
    - cd $GOPATH/src/gua
    - make build/linux
  artifacts:
    when: on_success
    name: "gua_${CI_BUILD_NAME}_${CI_BUILD_REF_NAME}"
    paths:
    - build/
  only:
  - tags
build:darwin:
  image: golang:1.12.1
  stage: build
  script:
    - export GO111MODULE=on
    - ln -s $PWD $GOPATH/src/gua
    - cd $GOPATH/src/gua
    - make build/darwin
  artifacts:
    when: on_success
    name: "gua_${CI_BUILD_NAME}_${CI_BUILD_REF_NAME}"
    paths:
    - build/
  only:
  - tags
