// Code generated by protoc-gen-go. DO NOT EDIT.
// source: job.proto

package delayquene

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Job struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=Id,proto3" json:"Id,omitempty"`
	Exectime             int64    `protobuf:"varint,3,opt,name=exectime,proto3" json:"exectime,omitempty"`
	RegisterTime         int64    `protobuf:"varint,4,opt,name=register_time,json=registerTime,proto3" json:"register_time,omitempty"`
	Timeout              int64    `protobuf:"varint,5,opt,name=timeout,proto3" json:"timeout,omitempty"`
	IntervalPattern      string   `protobuf:"bytes,6,opt,name=interval_pattern,json=intervalPattern,proto3" json:"interval_pattern,omitempty"`
	RequestUrl           string   `protobuf:"bytes,7,opt,name=request_url,json=requestUrl,proto3" json:"request_url,omitempty"`
	LuaBody              []byte   `protobuf:"bytes,8,opt,name=lua_body,json=luaBody,proto3" json:"lua_body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Job) Reset()         { *m = Job{} }
func (m *Job) String() string { return proto.CompactTextString(m) }
func (*Job) ProtoMessage()    {}
func (*Job) Descriptor() ([]byte, []int) {
	return fileDescriptor_f32c477d91a04ead, []int{0}
}

func (m *Job) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Job.Unmarshal(m, b)
}
func (m *Job) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Job.Marshal(b, m, deterministic)
}
func (m *Job) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Job.Merge(m, src)
}
func (m *Job) XXX_Size() int {
	return xxx_messageInfo_Job.Size(m)
}
func (m *Job) XXX_DiscardUnknown() {
	xxx_messageInfo_Job.DiscardUnknown(m)
}

var xxx_messageInfo_Job proto.InternalMessageInfo

func (m *Job) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Job) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Job) GetExectime() int64 {
	if m != nil {
		return m.Exectime
	}
	return 0
}

func (m *Job) GetRegisterTime() int64 {
	if m != nil {
		return m.RegisterTime
	}
	return 0
}

func (m *Job) GetTimeout() int64 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

func (m *Job) GetIntervalPattern() string {
	if m != nil {
		return m.IntervalPattern
	}
	return ""
}

func (m *Job) GetRequestUrl() string {
	if m != nil {
		return m.RequestUrl
	}
	return ""
}

func (m *Job) GetLuaBody() []byte {
	if m != nil {
		return m.LuaBody
	}
	return nil
}

func init() {
	proto.RegisterType((*Job)(nil), "delayquene.Job")
}

func init() { proto.RegisterFile("job.proto", fileDescriptor_f32c477d91a04ead) }

var fileDescriptor_f32c477d91a04ead = []byte{
	// 220 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0x90, 0x3d, 0x4e, 0xc3, 0x40,
	0x10, 0x85, 0xb5, 0x76, 0x88, 0x9d, 0x21, 0xfc, 0x68, 0xaa, 0x85, 0x06, 0x0b, 0x1a, 0xd3, 0xd0,
	0x70, 0x03, 0xba, 0x50, 0x21, 0x0b, 0x6a, 0x6b, 0xcd, 0x8e, 0x90, 0xd1, 0xc6, 0x9b, 0x4c, 0x66,
	0x11, 0x3e, 0x33, 0x97, 0x40, 0x1e, 0x70, 0xba, 0x79, 0xdf, 0xfb, 0xa4, 0x91, 0x1e, 0xac, 0x3e,
	0x63, 0xf7, 0xb0, 0xe3, 0x28, 0x11, 0xc1, 0x53, 0x70, 0xe3, 0x3e, 0xd1, 0x40, 0xb7, 0x3f, 0x06,
	0xf2, 0xe7, 0xd8, 0x21, 0xc2, 0x62, 0x70, 0x5b, 0xb2, 0xa6, 0x32, 0xf5, 0xaa, 0xd1, 0x1b, 0xcf,
	0x21, 0xdb, 0x78, 0x9b, 0x29, 0xc9, 0x36, 0x1e, 0xaf, 0xa1, 0xa4, 0x6f, 0x7a, 0x97, 0x7e, 0x4b,
	0x36, 0xaf, 0x4c, 0x9d, 0x37, 0xc7, 0x8c, 0x77, 0x70, 0xc6, 0xf4, 0xd1, 0x1f, 0x84, 0xb8, 0x55,
	0x61, 0xa1, 0xc2, 0x7a, 0x86, 0xaf, 0x93, 0x64, 0xa1, 0x98, 0xba, 0x98, 0xc4, 0x9e, 0x68, 0x3d,
	0x47, 0xbc, 0x87, 0xcb, 0x7e, 0x10, 0xe2, 0x2f, 0x17, 0xda, 0x9d, 0x13, 0x21, 0x1e, 0xec, 0x52,
	0x1f, 0x5f, 0xcc, 0xfc, 0xe5, 0x0f, 0xe3, 0x0d, 0x9c, 0x32, 0xed, 0x13, 0x1d, 0xa4, 0x4d, 0x1c,
	0x6c, 0xa1, 0x16, 0xfc, 0xa3, 0x37, 0x0e, 0x78, 0x05, 0x65, 0x48, 0xae, 0xed, 0xa2, 0x1f, 0x6d,
	0x59, 0x99, 0x7a, 0xdd, 0x14, 0x21, 0xb9, 0xa7, 0xe8, 0xc7, 0x6e, 0xa9, 0x03, 0x3c, 0xfe, 0x06,
	0x00, 0x00, 0xff, 0xff, 0xb6, 0x8b, 0x77, 0xb8, 0x0d, 0x01, 0x00, 0x00,
}
