// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gua.proto

package guaproto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type JobReplyRequest struct {
	JobId                string   `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Output               string   `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
	OtpCode              string   `protobuf:"bytes,3,opt,name=otp_code,json=otpCode,proto3" json:"otp_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JobReplyRequest) Reset()         { *m = JobReplyRequest{} }
func (m *JobReplyRequest) String() string { return proto.CompactTextString(m) }
func (*JobReplyRequest) ProtoMessage()    {}
func (*JobReplyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_55c0f4d918b61ad5, []int{0}
}

func (m *JobReplyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobReplyRequest.Unmarshal(m, b)
}
func (m *JobReplyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobReplyRequest.Marshal(b, m, deterministic)
}
func (m *JobReplyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobReplyRequest.Merge(m, src)
}
func (m *JobReplyRequest) XXX_Size() int {
	return xxx_messageInfo_JobReplyRequest.Size(m)
}
func (m *JobReplyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_JobReplyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_JobReplyRequest proto.InternalMessageInfo

func (m *JobReplyRequest) GetJobId() string {
	if m != nil {
		return m.JobId
	}
	return ""
}

func (m *JobReplyRequest) GetOutput() string {
	if m != nil {
		return m.Output
	}
	return ""
}

func (m *JobReplyRequest) GetOtpCode() string {
	if m != nil {
		return m.OtpCode
	}
	return ""
}

type JobReplyResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JobReplyResponse) Reset()         { *m = JobReplyResponse{} }
func (m *JobReplyResponse) String() string { return proto.CompactTextString(m) }
func (*JobReplyResponse) ProtoMessage()    {}
func (*JobReplyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_55c0f4d918b61ad5, []int{1}
}

func (m *JobReplyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobReplyResponse.Unmarshal(m, b)
}
func (m *JobReplyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobReplyResponse.Marshal(b, m, deterministic)
}
func (m *JobReplyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobReplyResponse.Merge(m, src)
}
func (m *JobReplyResponse) XXX_Size() int {
	return xxx_messageInfo_JobReplyResponse.Size(m)
}
func (m *JobReplyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_JobReplyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_JobReplyResponse proto.InternalMessageInfo

type NodeRegisterRequest struct {
	Hostname             string   `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Ip                   string   `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Mac                  string   `protobuf:"bytes,3,opt,name=mac,proto3" json:"mac,omitempty"`
	OtpToken             string   `protobuf:"bytes,4,opt,name=otp_token,json=otpToken,proto3" json:"otp_token,omitempty"`
	MachineCode          string   `protobuf:"bytes,5,opt,name=machine_code,json=machineCode,proto3" json:"machine_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeRegisterRequest) Reset()         { *m = NodeRegisterRequest{} }
func (m *NodeRegisterRequest) String() string { return proto.CompactTextString(m) }
func (*NodeRegisterRequest) ProtoMessage()    {}
func (*NodeRegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_55c0f4d918b61ad5, []int{2}
}

func (m *NodeRegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeRegisterRequest.Unmarshal(m, b)
}
func (m *NodeRegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeRegisterRequest.Marshal(b, m, deterministic)
}
func (m *NodeRegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeRegisterRequest.Merge(m, src)
}
func (m *NodeRegisterRequest) XXX_Size() int {
	return xxx_messageInfo_NodeRegisterRequest.Size(m)
}
func (m *NodeRegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeRegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NodeRegisterRequest proto.InternalMessageInfo

func (m *NodeRegisterRequest) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *NodeRegisterRequest) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *NodeRegisterRequest) GetMac() string {
	if m != nil {
		return m.Mac
	}
	return ""
}

func (m *NodeRegisterRequest) GetOtpToken() string {
	if m != nil {
		return m.OtpToken
	}
	return ""
}

func (m *NodeRegisterRequest) GetMachineCode() string {
	if m != nil {
		return m.MachineCode
	}
	return ""
}

type NodeRegisterResponse struct {
	NodeId               int64    `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeRegisterResponse) Reset()         { *m = NodeRegisterResponse{} }
func (m *NodeRegisterResponse) String() string { return proto.CompactTextString(m) }
func (*NodeRegisterResponse) ProtoMessage()    {}
func (*NodeRegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_55c0f4d918b61ad5, []int{3}
}

func (m *NodeRegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeRegisterResponse.Unmarshal(m, b)
}
func (m *NodeRegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeRegisterResponse.Marshal(b, m, deterministic)
}
func (m *NodeRegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeRegisterResponse.Merge(m, src)
}
func (m *NodeRegisterResponse) XXX_Size() int {
	return xxx_messageInfo_NodeRegisterResponse.Size(m)
}
func (m *NodeRegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeRegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NodeRegisterResponse proto.InternalMessageInfo

func (m *NodeRegisterResponse) GetNodeId() int64 {
	if m != nil {
		return m.NodeId
	}
	return 0
}

type Ping struct {
	NodeId               int64    `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ping) Reset()         { *m = Ping{} }
func (m *Ping) String() string { return proto.CompactTextString(m) }
func (*Ping) ProtoMessage()    {}
func (*Ping) Descriptor() ([]byte, []int) {
	return fileDescriptor_55c0f4d918b61ad5, []int{4}
}

func (m *Ping) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ping.Unmarshal(m, b)
}
func (m *Ping) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ping.Marshal(b, m, deterministic)
}
func (m *Ping) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ping.Merge(m, src)
}
func (m *Ping) XXX_Size() int {
	return xxx_messageInfo_Ping.Size(m)
}
func (m *Ping) XXX_DiscardUnknown() {
	xxx_messageInfo_Ping.DiscardUnknown(m)
}

var xxx_messageInfo_Ping proto.InternalMessageInfo

func (m *Ping) GetNodeId() int64 {
	if m != nil {
		return m.NodeId
	}
	return 0
}

type Pong struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pong) Reset()         { *m = Pong{} }
func (m *Pong) String() string { return proto.CompactTextString(m) }
func (*Pong) ProtoMessage()    {}
func (*Pong) Descriptor() ([]byte, []int) {
	return fileDescriptor_55c0f4d918b61ad5, []int{5}
}

func (m *Pong) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pong.Unmarshal(m, b)
}
func (m *Pong) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pong.Marshal(b, m, deterministic)
}
func (m *Pong) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pong.Merge(m, src)
}
func (m *Pong) XXX_Size() int {
	return xxx_messageInfo_Pong.Size(m)
}
func (m *Pong) XXX_DiscardUnknown() {
	xxx_messageInfo_Pong.DiscardUnknown(m)
}

var xxx_messageInfo_Pong proto.InternalMessageInfo

func init() {
	proto.RegisterType((*JobReplyRequest)(nil), "guaproto.JobReplyRequest")
	proto.RegisterType((*JobReplyResponse)(nil), "guaproto.JobReplyResponse")
	proto.RegisterType((*NodeRegisterRequest)(nil), "guaproto.NodeRegisterRequest")
	proto.RegisterType((*NodeRegisterResponse)(nil), "guaproto.NodeRegisterResponse")
	proto.RegisterType((*Ping)(nil), "guaproto.Ping")
	proto.RegisterType((*Pong)(nil), "guaproto.Pong")
}

func init() { proto.RegisterFile("gua.proto", fileDescriptor_55c0f4d918b61ad5) }

var fileDescriptor_55c0f4d918b61ad5 = []byte{
	// 332 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x51, 0x4d, 0x4f, 0xc2, 0x40,
	0x10, 0xa5, 0x14, 0x4a, 0x3b, 0x12, 0x24, 0xe3, 0x57, 0xa9, 0xf1, 0xab, 0x27, 0x2f, 0x62, 0xa2,
	0x3f, 0x81, 0x83, 0xe2, 0x41, 0x49, 0xe3, 0xcd, 0x03, 0xd9, 0xd2, 0x49, 0x29, 0xca, 0xce, 0x4a,
	0xb7, 0x07, 0x7f, 0x87, 0xff, 0xca, 0x5f, 0x65, 0x5a, 0x5a, 0x40, 0x03, 0xb7, 0x79, 0xf3, 0x66,
	0xe7, 0xbd, 0x7d, 0x03, 0x4e, 0x9c, 0x89, 0xbe, 0x5a, 0xb0, 0x66, 0xb4, 0xe3, 0x4c, 0x14, 0x95,
	0xff, 0x06, 0xfb, 0x4f, 0x1c, 0x06, 0xa4, 0x3e, 0xbe, 0x02, 0xfa, 0xcc, 0x28, 0xd5, 0x78, 0x04,
	0xd6, 0x8c, 0xc3, 0x71, 0x12, 0xb9, 0xc6, 0xa5, 0x71, 0xed, 0x04, 0xcd, 0x19, 0x87, 0xc3, 0x08,
	0x8f, 0xc1, 0xe2, 0x4c, 0xab, 0x4c, 0xbb, 0xf5, 0xa2, 0x5d, 0x22, 0xec, 0x81, 0xcd, 0x5a, 0x8d,
	0x27, 0x1c, 0x91, 0x6b, 0x16, 0x4c, 0x8b, 0xb5, 0x1a, 0x70, 0x44, 0x3e, 0x42, 0x77, 0xbd, 0x3c,
	0x55, 0x2c, 0x53, 0xf2, 0xbf, 0x0d, 0x38, 0x78, 0xe6, 0x88, 0x02, 0x8a, 0x93, 0x54, 0xd3, 0xa2,
	0x52, 0xf5, 0xc0, 0x9e, 0x72, 0xaa, 0xa5, 0x98, 0x53, 0xa9, 0xbb, 0xc2, 0xd8, 0x81, 0x7a, 0xa2,
	0x4a, 0xd9, 0x7a, 0xa2, 0xb0, 0x0b, 0xe6, 0x5c, 0x4c, 0x4a, 0xb5, 0xbc, 0xc4, 0x53, 0x70, 0x72,
	0x13, 0x9a, 0xdf, 0x49, 0xba, 0x8d, 0xe5, 0x73, 0xd6, 0xea, 0x35, 0xc7, 0x78, 0x05, 0xed, 0xb9,
	0x98, 0x4c, 0x13, 0x49, 0x4b, 0x97, 0xcd, 0x82, 0xdf, 0x2b, 0x7b, 0x85, 0xd3, 0x5b, 0x38, 0xfc,
	0x6b, 0x6a, 0xe9, 0x16, 0x4f, 0xa0, 0x25, 0x39, 0xa2, 0x2a, 0x0c, 0x33, 0xb0, 0x72, 0x38, 0x8c,
	0xfc, 0x0b, 0x68, 0x8c, 0x12, 0x19, 0xef, 0x1e, 0xb0, 0xa0, 0x31, 0x62, 0x19, 0xdf, 0xfd, 0x18,
	0x60, 0x3e, 0x64, 0x02, 0x5f, 0xa0, 0xbd, 0xa9, 0x80, 0x67, 0xfd, 0xea, 0x06, 0xfd, 0x2d, 0x71,
	0x78, 0xe7, 0xbb, 0xe8, 0x32, 0xc6, 0x1a, 0x0e, 0xc0, 0xae, 0xc2, 0xc5, 0xde, 0x7a, 0xfa, 0xdf,
	0x35, 0x3d, 0x6f, 0x1b, 0xb5, 0x5a, 0x72, 0x03, 0xce, 0x23, 0x89, 0x85, 0x0e, 0x49, 0x68, 0xec,
	0xac, 0x47, 0xf3, 0xbf, 0x79, 0x9b, 0x98, 0x65, 0xec, 0xd7, 0x42, 0xab, 0x40, 0xf7, 0xbf, 0x01,
	0x00, 0x00, 0xff, 0xff, 0x7f, 0xb7, 0x50, 0x79, 0x4b, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GuaClient is the client API for Gua service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GuaClient interface {
	NodeRegister(ctx context.Context, in *NodeRegisterRequest, opts ...grpc.CallOption) (*NodeRegisterResponse, error)
	JobReply(ctx context.Context, in *JobReplyRequest, opts ...grpc.CallOption) (*JobReplyResponse, error)
	Heartbeat(ctx context.Context, in *Ping, opts ...grpc.CallOption) (*Pong, error)
}

type guaClient struct {
	cc *grpc.ClientConn
}

func NewGuaClient(cc *grpc.ClientConn) GuaClient {
	return &guaClient{cc}
}

func (c *guaClient) NodeRegister(ctx context.Context, in *NodeRegisterRequest, opts ...grpc.CallOption) (*NodeRegisterResponse, error) {
	out := new(NodeRegisterResponse)
	err := c.cc.Invoke(ctx, "/guaproto.Gua/NodeRegister", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guaClient) JobReply(ctx context.Context, in *JobReplyRequest, opts ...grpc.CallOption) (*JobReplyResponse, error) {
	out := new(JobReplyResponse)
	err := c.cc.Invoke(ctx, "/guaproto.Gua/JobReply", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guaClient) Heartbeat(ctx context.Context, in *Ping, opts ...grpc.CallOption) (*Pong, error) {
	out := new(Pong)
	err := c.cc.Invoke(ctx, "/guaproto.Gua/Heartbeat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GuaServer is the server API for Gua service.
type GuaServer interface {
	NodeRegister(context.Context, *NodeRegisterRequest) (*NodeRegisterResponse, error)
	JobReply(context.Context, *JobReplyRequest) (*JobReplyResponse, error)
	Heartbeat(context.Context, *Ping) (*Pong, error)
}

func RegisterGuaServer(s *grpc.Server, srv GuaServer) {
	s.RegisterService(&_Gua_serviceDesc, srv)
}

func _Gua_NodeRegister_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeRegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuaServer).NodeRegister(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/guaproto.Gua/NodeRegister",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuaServer).NodeRegister(ctx, req.(*NodeRegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gua_JobReply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JobReplyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuaServer).JobReply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/guaproto.Gua/JobReply",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuaServer).JobReply(ctx, req.(*JobReplyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gua_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Ping)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuaServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/guaproto.Gua/Heartbeat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuaServer).Heartbeat(ctx, req.(*Ping))
	}
	return interceptor(ctx, in, info, handler)
}

var _Gua_serviceDesc = grpc.ServiceDesc{
	ServiceName: "guaproto.Gua",
	HandlerType: (*GuaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NodeRegister",
			Handler:    _Gua_NodeRegister_Handler,
		},
		{
			MethodName: "JobReply",
			Handler:    _Gua_JobReply_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _Gua_Heartbeat_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gua.proto",
}
