// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.1
// source: gua.proto

package guaproto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	GuaAdmin_RegisterGroup_FullMethodName = "/guaproto.GuaAdmin/RegisterGroup"
	GuaAdmin_RemoveGroup_FullMethodName   = "/guaproto.GuaAdmin/RemoveGroup"
	GuaAdmin_AddJob_FullMethodName        = "/guaproto.GuaAdmin/AddJob"
	GuaAdmin_EditJob_FullMethodName       = "/guaproto.GuaAdmin/EditJob"
	GuaAdmin_DeleteJob_FullMethodName     = "/guaproto.GuaAdmin/DeleteJob"
	GuaAdmin_PauseJob_FullMethodName      = "/guaproto.GuaAdmin/PauseJob"
	GuaAdmin_ActiveJob_FullMethodName     = "/guaproto.GuaAdmin/ActiveJob"
	GuaAdmin_ListJobs_FullMethodName      = "/guaproto.GuaAdmin/ListJobs"
)

// GuaAdminClient is the client API for GuaAdmin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GuaAdminClient interface {
	RegisterGroup(ctx context.Context, in *GroupRequest, opts ...grpc.CallOption) (*Empty, error)
	RemoveGroup(ctx context.Context, in *GroupRequest, opts ...grpc.CallOption) (*Empty, error)
	AddJob(ctx context.Context, in *AddJobRequest, opts ...grpc.CallOption) (*AddJobResponse, error)
	EditJob(ctx context.Context, in *EditJobRequest, opts ...grpc.CallOption) (*Empty, error)
	DeleteJob(ctx context.Context, in *JobRef, opts ...grpc.CallOption) (*Empty, error)
	PauseJob(ctx context.Context, in *JobRef, opts ...grpc.CallOption) (*Empty, error)
	ActiveJob(ctx context.Context, in *ActiveJobRequest, opts ...grpc.CallOption) (*Empty, error)
	ListJobs(ctx context.Context, in *GroupRequest, opts ...grpc.CallOption) (*ListJobsResponse, error)
}

type guaAdminClient struct {
	cc grpc.ClientConnInterface
}

func NewGuaAdminClient(cc grpc.ClientConnInterface) GuaAdminClient {
	return &guaAdminClient{cc}
}

func (c *guaAdminClient) RegisterGroup(ctx context.Context, in *GroupRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, GuaAdmin_RegisterGroup_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guaAdminClient) RemoveGroup(ctx context.Context, in *GroupRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, GuaAdmin_RemoveGroup_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guaAdminClient) AddJob(ctx context.Context, in *AddJobRequest, opts ...grpc.CallOption) (*AddJobResponse, error) {
	out := new(AddJobResponse)
	err := c.cc.Invoke(ctx, GuaAdmin_AddJob_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guaAdminClient) EditJob(ctx context.Context, in *EditJobRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, GuaAdmin_EditJob_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guaAdminClient) DeleteJob(ctx context.Context, in *JobRef, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, GuaAdmin_DeleteJob_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guaAdminClient) PauseJob(ctx context.Context, in *JobRef, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, GuaAdmin_PauseJob_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guaAdminClient) ActiveJob(ctx context.Context, in *ActiveJobRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, GuaAdmin_ActiveJob_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guaAdminClient) ListJobs(ctx context.Context, in *GroupRequest, opts ...grpc.CallOption) (*ListJobsResponse, error) {
	out := new(ListJobsResponse)
	err := c.cc.Invoke(ctx, GuaAdmin_ListJobs_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GuaAdminServer is the server API for GuaAdmin service.
// All implementations should embed UnimplementedGuaAdminServer
// for forward compatibility
type GuaAdminServer interface {
	RegisterGroup(context.Context, *GroupRequest) (*Empty, error)
	RemoveGroup(context.Context, *GroupRequest) (*Empty, error)
	AddJob(context.Context, *AddJobRequest) (*AddJobResponse, error)
	EditJob(context.Context, *EditJobRequest) (*Empty, error)
	DeleteJob(context.Context, *JobRef) (*Empty, error)
	PauseJob(context.Context, *JobRef) (*Empty, error)
	ActiveJob(context.Context, *ActiveJobRequest) (*Empty, error)
	ListJobs(context.Context, *GroupRequest) (*ListJobsResponse, error)
}

// UnimplementedGuaAdminServer should be embedded to have forward compatible implementations.
type UnimplementedGuaAdminServer struct {
}

func (UnimplementedGuaAdminServer) RegisterGroup(context.Context, *GroupRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterGroup not implemented")
}
func (UnimplementedGuaAdminServer) RemoveGroup(context.Context, *GroupRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveGroup not implemented")
}
func (UnimplementedGuaAdminServer) AddJob(context.Context, *AddJobRequest) (*AddJobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddJob not implemented")
}
func (UnimplementedGuaAdminServer) EditJob(context.Context, *EditJobRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EditJob not implemented")
}
func (UnimplementedGuaAdminServer) DeleteJob(context.Context, *JobRef) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteJob not implemented")
}
func (UnimplementedGuaAdminServer) PauseJob(context.Context, *JobRef) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PauseJob not implemented")
}
func (UnimplementedGuaAdminServer) ActiveJob(context.Context, *ActiveJobRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ActiveJob not implemented")
}
func (UnimplementedGuaAdminServer) ListJobs(context.Context, *GroupRequest) (*ListJobsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListJobs not implemented")
}

// UnsafeGuaAdminServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GuaAdminServer will
// result in compilation errors.
type UnsafeGuaAdminServer interface {
	mustEmbedUnimplementedGuaAdminServer()
}

func RegisterGuaAdminServer(s grpc.ServiceRegistrar, srv GuaAdminServer) {
	s.RegisterService(&GuaAdmin_ServiceDesc, srv)
}

func _GuaAdmin_RegisterGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuaAdminServer).RegisterGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GuaAdmin_RegisterGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuaAdminServer).RegisterGroup(ctx, req.(*GroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuaAdmin_RemoveGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuaAdminServer).RemoveGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GuaAdmin_RemoveGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuaAdminServer).RemoveGroup(ctx, req.(*GroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuaAdmin_AddJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuaAdminServer).AddJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GuaAdmin_AddJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuaAdminServer).AddJob(ctx, req.(*AddJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuaAdmin_EditJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuaAdminServer).EditJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GuaAdmin_EditJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuaAdminServer).EditJob(ctx, req.(*EditJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuaAdmin_DeleteJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JobRef)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuaAdminServer).DeleteJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GuaAdmin_DeleteJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuaAdminServer).DeleteJob(ctx, req.(*JobRef))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuaAdmin_PauseJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JobRef)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuaAdminServer).PauseJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GuaAdmin_PauseJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuaAdminServer).PauseJob(ctx, req.(*JobRef))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuaAdmin_ActiveJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActiveJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuaAdminServer).ActiveJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GuaAdmin_ActiveJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuaAdminServer).ActiveJob(ctx, req.(*ActiveJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuaAdmin_ListJobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuaAdminServer).ListJobs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GuaAdmin_ListJobs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuaAdminServer).ListJobs(ctx, req.(*GroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GuaAdmin_ServiceDesc is the grpc.ServiceDesc for GuaAdmin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GuaAdmin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "guaproto.GuaAdmin",
	HandlerType: (*GuaAdminServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterGroup",
			Handler:    _GuaAdmin_RegisterGroup_Handler,
		},
		{
			MethodName: "RemoveGroup",
			Handler:    _GuaAdmin_RemoveGroup_Handler,
		},
		{
			MethodName: "AddJob",
			Handler:    _GuaAdmin_AddJob_Handler,
		},
		{
			MethodName: "EditJob",
			Handler:    _GuaAdmin_EditJob_Handler,
		},
		{
			MethodName: "DeleteJob",
			Handler:    _GuaAdmin_DeleteJob_Handler,
		},
		{
			MethodName: "PauseJob",
			Handler:    _GuaAdmin_PauseJob_Handler,
		},
		{
			MethodName: "ActiveJob",
			Handler:    _GuaAdmin_ActiveJob_Handler,
		},
		{
			MethodName: "ListJobs",
			Handler:    _GuaAdmin_ListJobs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gua.proto",
}

const (
	GuaCallback_OnJobTrigger_FullMethodName = "/guaproto.GuaCallback/OnJobTrigger"
)

// GuaCallbackClient is the client API for GuaCallback service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GuaCallbackClient interface {
	OnJobTrigger(ctx context.Context, in *JobTrigger, opts ...grpc.CallOption) (*JobResult, error)
}

type guaCallbackClient struct {
	cc grpc.ClientConnInterface
}

func NewGuaCallbackClient(cc grpc.ClientConnInterface) GuaCallbackClient {
	return &guaCallbackClient{cc}
}

func (c *guaCallbackClient) OnJobTrigger(ctx context.Context, in *JobTrigger, opts ...grpc.CallOption) (*JobResult, error) {
	out := new(JobResult)
	err := c.cc.Invoke(ctx, GuaCallback_OnJobTrigger_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GuaCallbackServer is the server API for GuaCallback service.
// All implementations should embed UnimplementedGuaCallbackServer
// for forward compatibility
type GuaCallbackServer interface {
	OnJobTrigger(context.Context, *JobTrigger) (*JobResult, error)
}

// UnimplementedGuaCallbackServer should be embedded to have forward compatible implementations.
type UnimplementedGuaCallbackServer struct {
}

func (UnimplementedGuaCallbackServer) OnJobTrigger(context.Context, *JobTrigger) (*JobResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OnJobTrigger not implemented")
}

// UnsafeGuaCallbackServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GuaCallbackServer will
// result in compilation errors.
type UnsafeGuaCallbackServer interface {
	mustEmbedUnimplementedGuaCallbackServer()
}

func RegisterGuaCallbackServer(s grpc.ServiceRegistrar, srv GuaCallbackServer) {
	s.RegisterService(&GuaCallback_ServiceDesc, srv)
}

func _GuaCallback_OnJobTrigger_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JobTrigger)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuaCallbackServer).OnJobTrigger(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GuaCallback_OnJobTrigger_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuaCallbackServer).OnJobTrigger(ctx, req.(*JobTrigger))
	}
	return interceptor(ctx, in, info, handler)
}

// GuaCallback_ServiceDesc is the grpc.ServiceDesc for GuaCallback service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GuaCallback_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "guaproto.GuaCallback",
	HandlerType: (*GuaCallbackServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OnJobTrigger",
			Handler:    _GuaCallback_OnJobTrigger_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gua.proto",
}
