// Code generated by protoc-gen-go. DO NOT EDIT.
// source: job.proto

package guaproto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Job struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=Id,proto3" json:"Id,omitempty"`
	Exectime             int64    `protobuf:"varint,3,opt,name=exectime,proto3" json:"exectime,omitempty"`
	OtpToken             string   `protobuf:"bytes,4,opt,name=otp_token,json=otpToken,proto3" json:"otp_token,omitempty"`
	Timeout              int64    `protobuf:"varint,5,opt,name=timeout,proto3" json:"timeout,omitempty"`
	IntervalPattern      string   `protobuf:"bytes,6,opt,name=interval_pattern,json=intervalPattern,proto3" json:"interval_pattern,omitempty"`
	RequestUrl           string   `protobuf:"bytes,7,opt,name=request_url,json=requestUrl,proto3" json:"request_url,omitempty"`
	ExecCmd              []byte   `protobuf:"bytes,8,opt,name=exec_cmd,json=execCmd,proto3" json:"exec_cmd,omitempty"`
	GroupName            string   `protobuf:"bytes,9,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`
	Active               bool     `protobuf:"varint,10,opt,name=active,proto3" json:"active,omitempty"`
	Memo                 string   `protobuf:"bytes,11,opt,name=memo,proto3" json:"memo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Job) Reset()         { *m = Job{} }
func (m *Job) String() string { return proto.CompactTextString(m) }
func (*Job) ProtoMessage()    {}
func (*Job) Descriptor() ([]byte, []int) {
	return fileDescriptor_f32c477d91a04ead, []int{0}
}

func (m *Job) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Job.Unmarshal(m, b)
}
func (m *Job) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Job.Marshal(b, m, deterministic)
}
func (m *Job) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Job.Merge(m, src)
}
func (m *Job) XXX_Size() int {
	return xxx_messageInfo_Job.Size(m)
}
func (m *Job) XXX_DiscardUnknown() {
	xxx_messageInfo_Job.DiscardUnknown(m)
}

var xxx_messageInfo_Job proto.InternalMessageInfo

func (m *Job) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Job) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Job) GetExectime() int64 {
	if m != nil {
		return m.Exectime
	}
	return 0
}

func (m *Job) GetOtpToken() string {
	if m != nil {
		return m.OtpToken
	}
	return ""
}

func (m *Job) GetTimeout() int64 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

func (m *Job) GetIntervalPattern() string {
	if m != nil {
		return m.IntervalPattern
	}
	return ""
}

func (m *Job) GetRequestUrl() string {
	if m != nil {
		return m.RequestUrl
	}
	return ""
}

func (m *Job) GetExecCmd() []byte {
	if m != nil {
		return m.ExecCmd
	}
	return nil
}

func (m *Job) GetGroupName() string {
	if m != nil {
		return m.GroupName
	}
	return ""
}

func (m *Job) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

func (m *Job) GetMemo() string {
	if m != nil {
		return m.Memo
	}
	return ""
}

type ReadyJob struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=Id,proto3" json:"Id,omitempty"`
	OtpToken             string   `protobuf:"bytes,3,opt,name=otp_token,json=otpToken,proto3" json:"otp_token,omitempty"`
	Timeout              int64    `protobuf:"varint,4,opt,name=timeout,proto3" json:"timeout,omitempty"`
	RequestUrl           string   `protobuf:"bytes,5,opt,name=request_url,json=requestUrl,proto3" json:"request_url,omitempty"`
	ExecCmd              []byte   `protobuf:"bytes,6,opt,name=exec_cmd,json=execCmd,proto3" json:"exec_cmd,omitempty"`
	PlanTime             int64    `protobuf:"varint,7,opt,name=plan_time,json=planTime,proto3" json:"plan_time,omitempty"`
	GetJobTime           int64    `protobuf:"varint,8,opt,name=get_job_time,json=getJobTime,proto3" json:"get_job_time,omitempty"`
	GetJobMachineHost    string   `protobuf:"bytes,9,opt,name=get_job_machine_host,json=getJobMachineHost,proto3" json:"get_job_machine_host,omitempty"`
	GetJobMachineMac     string   `protobuf:"bytes,10,opt,name=get_job_machine_mac,json=getJobMachineMac,proto3" json:"get_job_machine_mac,omitempty"`
	GetJobMachineIp      string   `protobuf:"bytes,11,opt,name=get_job_machine_ip,json=getJobMachineIp,proto3" json:"get_job_machine_ip,omitempty"`
	GroupName            string   `protobuf:"bytes,12,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadyJob) Reset()         { *m = ReadyJob{} }
func (m *ReadyJob) String() string { return proto.CompactTextString(m) }
func (*ReadyJob) ProtoMessage()    {}
func (*ReadyJob) Descriptor() ([]byte, []int) {
	return fileDescriptor_f32c477d91a04ead, []int{1}
}

func (m *ReadyJob) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadyJob.Unmarshal(m, b)
}
func (m *ReadyJob) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadyJob.Marshal(b, m, deterministic)
}
func (m *ReadyJob) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadyJob.Merge(m, src)
}
func (m *ReadyJob) XXX_Size() int {
	return xxx_messageInfo_ReadyJob.Size(m)
}
func (m *ReadyJob) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadyJob.DiscardUnknown(m)
}

var xxx_messageInfo_ReadyJob proto.InternalMessageInfo

func (m *ReadyJob) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReadyJob) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ReadyJob) GetOtpToken() string {
	if m != nil {
		return m.OtpToken
	}
	return ""
}

func (m *ReadyJob) GetTimeout() int64 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

func (m *ReadyJob) GetRequestUrl() string {
	if m != nil {
		return m.RequestUrl
	}
	return ""
}

func (m *ReadyJob) GetExecCmd() []byte {
	if m != nil {
		return m.ExecCmd
	}
	return nil
}

func (m *ReadyJob) GetPlanTime() int64 {
	if m != nil {
		return m.PlanTime
	}
	return 0
}

func (m *ReadyJob) GetGetJobTime() int64 {
	if m != nil {
		return m.GetJobTime
	}
	return 0
}

func (m *ReadyJob) GetGetJobMachineHost() string {
	if m != nil {
		return m.GetJobMachineHost
	}
	return ""
}

func (m *ReadyJob) GetGetJobMachineMac() string {
	if m != nil {
		return m.GetJobMachineMac
	}
	return ""
}

func (m *ReadyJob) GetGetJobMachineIp() string {
	if m != nil {
		return m.GetJobMachineIp
	}
	return ""
}

func (m *ReadyJob) GetGroupName() string {
	if m != nil {
		return m.GroupName
	}
	return ""
}

type Func struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	GroupName            string   `protobuf:"bytes,2,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`
	UseOtp               bool     `protobuf:"varint,3,opt,name=use_otp,json=useOtp,proto3" json:"use_otp,omitempty"`
	DisableGroupOtp      bool     `protobuf:"varint,4,opt,name=disable_group_otp,json=disableGroupOtp,proto3" json:"disable_group_otp,omitempty"`
	OtpToken             string   `protobuf:"bytes,5,opt,name=otp_token,json=otpToken,proto3" json:"otp_token,omitempty"`
	LuaBody              []byte   `protobuf:"bytes,6,opt,name=LuaBody,proto3" json:"LuaBody,omitempty"`
	Active               bool     `protobuf:"varint,7,opt,name=active,proto3" json:"active,omitempty"`
	Memo                 string   `protobuf:"bytes,8,opt,name=memo,proto3" json:"memo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Func) Reset()         { *m = Func{} }
func (m *Func) String() string { return proto.CompactTextString(m) }
func (*Func) ProtoMessage()    {}
func (*Func) Descriptor() ([]byte, []int) {
	return fileDescriptor_f32c477d91a04ead, []int{2}
}

func (m *Func) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Func.Unmarshal(m, b)
}
func (m *Func) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Func.Marshal(b, m, deterministic)
}
func (m *Func) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Func.Merge(m, src)
}
func (m *Func) XXX_Size() int {
	return xxx_messageInfo_Func.Size(m)
}
func (m *Func) XXX_DiscardUnknown() {
	xxx_messageInfo_Func.DiscardUnknown(m)
}

var xxx_messageInfo_Func proto.InternalMessageInfo

func (m *Func) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Func) GetGroupName() string {
	if m != nil {
		return m.GroupName
	}
	return ""
}

func (m *Func) GetUseOtp() bool {
	if m != nil {
		return m.UseOtp
	}
	return false
}

func (m *Func) GetDisableGroupOtp() bool {
	if m != nil {
		return m.DisableGroupOtp
	}
	return false
}

func (m *Func) GetOtpToken() string {
	if m != nil {
		return m.OtpToken
	}
	return ""
}

func (m *Func) GetLuaBody() []byte {
	if m != nil {
		return m.LuaBody
	}
	return nil
}

func (m *Func) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

func (m *Func) GetMemo() string {
	if m != nil {
		return m.Memo
	}
	return ""
}

func init() {
	proto.RegisterType((*Job)(nil), "guaproto.Job")
	proto.RegisterType((*ReadyJob)(nil), "guaproto.ReadyJob")
	proto.RegisterType((*Func)(nil), "guaproto.Func")
}

func init() { proto.RegisterFile("job.proto", fileDescriptor_f32c477d91a04ead) }

var fileDescriptor_f32c477d91a04ead = []byte{
	// 462 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0x6d, 0x6e, 0xd4, 0x30,
	0x14, 0x54, 0x3e, 0x36, 0x71, 0x5e, 0x57, 0x6c, 0x6b, 0x10, 0x18, 0x2a, 0x44, 0xb4, 0xbf, 0x16,
	0x10, 0xf0, 0x83, 0x1b, 0x80, 0x04, 0x6c, 0x45, 0x01, 0x45, 0xe5, 0xb7, 0xe5, 0x24, 0x4f, 0xdb,
	0x94, 0x24, 0x36, 0x89, 0x5d, 0xd1, 0x3b, 0x70, 0x16, 0xee, 0xc4, 0x4d, 0x90, 0x9d, 0x2c, 0x90,
	0x50, 0x10, 0xff, 0x3c, 0xf3, 0x66, 0xa4, 0xbc, 0x99, 0x17, 0x48, 0x2e, 0x64, 0xfe, 0x54, 0x75,
	0x52, 0x4b, 0x4a, 0x76, 0x46, 0xb8, 0xd7, 0xfa, 0x9b, 0x0f, 0xc1, 0x89, 0xcc, 0x29, 0x85, 0xb0,
	0x15, 0x0d, 0x32, 0x2f, 0xf5, 0x36, 0x49, 0xe6, 0xde, 0xf4, 0x06, 0xf8, 0xdb, 0x92, 0xf9, 0x8e,
	0xf1, 0xb7, 0x25, 0xbd, 0x07, 0x04, 0xbf, 0x60, 0xa1, 0xab, 0x06, 0x59, 0x90, 0x7a, 0x9b, 0x20,
	0xfb, 0x89, 0xe9, 0x31, 0x24, 0x52, 0x2b, 0xae, 0xe5, 0x27, 0x6c, 0x59, 0xe8, 0x2c, 0x44, 0x6a,
	0x75, 0x66, 0x31, 0x65, 0x10, 0x5b, 0x91, 0x34, 0x9a, 0x2d, 0x9c, 0x6f, 0x0f, 0xe9, 0x43, 0x38,
	0xac, 0x5a, 0x8d, 0xdd, 0xa5, 0xa8, 0xb9, 0x12, 0x5a, 0x63, 0xd7, 0xb2, 0xc8, 0xb9, 0x57, 0x7b,
	0xfe, 0xc3, 0x40, 0xd3, 0x07, 0x70, 0xd0, 0xe1, 0x67, 0x83, 0xbd, 0xe6, 0xa6, 0xab, 0x59, 0xec,
	0x54, 0x30, 0x52, 0x1f, 0xbb, 0x9a, 0xde, 0x1d, 0x3e, 0x8f, 0x17, 0x4d, 0xc9, 0x48, 0xea, 0x6d,
	0x96, 0x59, 0x6c, 0xf1, 0xcb, 0xa6, 0xa4, 0xf7, 0x01, 0x76, 0x9d, 0x34, 0x8a, 0xbb, 0x1d, 0x13,
	0x67, 0x4d, 0x1c, 0xf3, 0xce, 0x2e, 0x7a, 0x1b, 0x22, 0x51, 0xe8, 0xea, 0x12, 0x19, 0xa4, 0xde,
	0x86, 0x64, 0x23, 0xb2, 0xa1, 0x34, 0xd8, 0x48, 0x76, 0x30, 0x84, 0x62, 0xdf, 0xeb, 0xaf, 0x01,
	0x90, 0x0c, 0x45, 0x79, 0xf5, 0xbf, 0xa9, 0x4d, 0x92, 0x09, 0xfe, 0x9e, 0x4c, 0x38, 0x4d, 0x66,
	0xb6, 0xee, 0xe2, 0x9f, 0xeb, 0x46, 0xd3, 0x75, 0x8f, 0x21, 0x51, 0xb5, 0x68, 0xb9, 0x6b, 0x2a,
	0x1e, 0x9a, 0xb2, 0xc4, 0x99, 0x6d, 0x2a, 0x85, 0xe5, 0x0e, 0x35, 0xbf, 0x90, 0xf9, 0x30, 0x27,
	0x6e, 0x0e, 0x3b, 0xd4, 0x27, 0x32, 0x77, 0x8a, 0x67, 0x70, 0x6b, 0xaf, 0x68, 0x44, 0x71, 0x5e,
	0xb5, 0xc8, 0xcf, 0x65, 0xaf, 0xc7, 0xdc, 0x8e, 0x06, 0xe5, 0xe9, 0x30, 0x79, 0x23, 0x7b, 0x4d,
	0x9f, 0xc0, 0xcd, 0xb9, 0xa1, 0x11, 0x85, 0x0b, 0x33, 0xc9, 0x0e, 0x27, 0xfa, 0x53, 0x51, 0xd0,
	0xc7, 0x40, 0xe7, 0xf2, 0x4a, 0x8d, 0x21, 0xaf, 0x26, 0xea, 0xad, 0x9a, 0x55, 0xb7, 0x9c, 0x55,
	0xb7, 0xfe, 0xee, 0x41, 0xf8, 0xca, 0xb4, 0xc5, 0xb5, 0x55, 0x4c, 0xbd, 0xfe, 0xbc, 0xf6, 0x3b,
	0x10, 0x9b, 0x1e, 0xb9, 0xd4, 0xca, 0xf5, 0x42, 0xb2, 0xc8, 0xf4, 0xf8, 0x5e, 0x2b, 0xfa, 0x08,
	0x8e, 0xca, 0xaa, 0x17, 0x79, 0x8d, 0x7c, 0xf0, 0x5b, 0x49, 0xe8, 0x24, 0xab, 0x71, 0xf0, 0xda,
	0xf2, 0x56, 0x3b, 0xa9, 0x77, 0xf1, 0x67, 0xbd, 0x6f, 0x8d, 0x78, 0x21, 0xcb, 0xab, 0x7d, 0x45,
	0x23, 0xfc, 0xed, 0xe4, 0xe2, 0x6b, 0x4f, 0x8e, 0xfc, 0x3a, 0xb9, 0x3c, 0x72, 0xbf, 0xea, 0xf3,
	0x1f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x48, 0xfd, 0x48, 0x2b, 0xc1, 0x03, 0x00, 0x00,
}
