// Code generated by protoc-gen-go. DO NOT EDIT.
// source: node.proto

package guaproto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RemoteCommandRequest struct {
	ExecCmd              []byte   `protobuf:"bytes,1,opt,name=exec_cmd,json=execCmd,proto3" json:"exec_cmd,omitempty"`
	JobId                string   `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Timeout              int64    `protobuf:"varint,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	OtpCode              string   `protobuf:"bytes,4,opt,name=otp_code,json=otpCode,proto3" json:"otp_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoteCommandRequest) Reset()         { *m = RemoteCommandRequest{} }
func (m *RemoteCommandRequest) String() string { return proto.CompactTextString(m) }
func (*RemoteCommandRequest) ProtoMessage()    {}
func (*RemoteCommandRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{0}
}

func (m *RemoteCommandRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoteCommandRequest.Unmarshal(m, b)
}
func (m *RemoteCommandRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoteCommandRequest.Marshal(b, m, deterministic)
}
func (m *RemoteCommandRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoteCommandRequest.Merge(m, src)
}
func (m *RemoteCommandRequest) XXX_Size() int {
	return xxx_messageInfo_RemoteCommandRequest.Size(m)
}
func (m *RemoteCommandRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoteCommandRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoteCommandRequest proto.InternalMessageInfo

func (m *RemoteCommandRequest) GetExecCmd() []byte {
	if m != nil {
		return m.ExecCmd
	}
	return nil
}

func (m *RemoteCommandRequest) GetJobId() string {
	if m != nil {
		return m.JobId
	}
	return ""
}

func (m *RemoteCommandRequest) GetTimeout() int64 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

func (m *RemoteCommandRequest) GetOtpCode() string {
	if m != nil {
		return m.OtpCode
	}
	return ""
}

type RemoteCommandResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoteCommandResponse) Reset()         { *m = RemoteCommandResponse{} }
func (m *RemoteCommandResponse) String() string { return proto.CompactTextString(m) }
func (*RemoteCommandResponse) ProtoMessage()    {}
func (*RemoteCommandResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{1}
}

func (m *RemoteCommandResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoteCommandResponse.Unmarshal(m, b)
}
func (m *RemoteCommandResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoteCommandResponse.Marshal(b, m, deterministic)
}
func (m *RemoteCommandResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoteCommandResponse.Merge(m, src)
}
func (m *RemoteCommandResponse) XXX_Size() int {
	return xxx_messageInfo_RemoteCommandResponse.Size(m)
}
func (m *RemoteCommandResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoteCommandResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RemoteCommandResponse proto.InternalMessageInfo

type RegisterCommandRequest struct {
	JobId                string   `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	OtpToken             string   `protobuf:"bytes,2,opt,name=otp_token,json=otpToken,proto3" json:"otp_token,omitempty"`
	OtpCode              string   `protobuf:"bytes,3,opt,name=otp_code,json=otpCode,proto3" json:"otp_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterCommandRequest) Reset()         { *m = RegisterCommandRequest{} }
func (m *RegisterCommandRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterCommandRequest) ProtoMessage()    {}
func (*RegisterCommandRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{2}
}

func (m *RegisterCommandRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterCommandRequest.Unmarshal(m, b)
}
func (m *RegisterCommandRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterCommandRequest.Marshal(b, m, deterministic)
}
func (m *RegisterCommandRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterCommandRequest.Merge(m, src)
}
func (m *RegisterCommandRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterCommandRequest.Size(m)
}
func (m *RegisterCommandRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterCommandRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterCommandRequest proto.InternalMessageInfo

func (m *RegisterCommandRequest) GetJobId() string {
	if m != nil {
		return m.JobId
	}
	return ""
}

func (m *RegisterCommandRequest) GetOtpToken() string {
	if m != nil {
		return m.OtpToken
	}
	return ""
}

func (m *RegisterCommandRequest) GetOtpCode() string {
	if m != nil {
		return m.OtpCode
	}
	return ""
}

type RegisterCommandReponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterCommandReponse) Reset()         { *m = RegisterCommandReponse{} }
func (m *RegisterCommandReponse) String() string { return proto.CompactTextString(m) }
func (*RegisterCommandReponse) ProtoMessage()    {}
func (*RegisterCommandReponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{3}
}

func (m *RegisterCommandReponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterCommandReponse.Unmarshal(m, b)
}
func (m *RegisterCommandReponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterCommandReponse.Marshal(b, m, deterministic)
}
func (m *RegisterCommandReponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterCommandReponse.Merge(m, src)
}
func (m *RegisterCommandReponse) XXX_Size() int {
	return xxx_messageInfo_RegisterCommandReponse.Size(m)
}
func (m *RegisterCommandReponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterCommandReponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterCommandReponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*RemoteCommandRequest)(nil), "guaproto.RemoteCommandRequest")
	proto.RegisterType((*RemoteCommandResponse)(nil), "guaproto.RemoteCommandResponse")
	proto.RegisterType((*RegisterCommandRequest)(nil), "guaproto.RegisterCommandRequest")
	proto.RegisterType((*RegisterCommandReponse)(nil), "guaproto.RegisterCommandReponse")
}

func init() { proto.RegisterFile("node.proto", fileDescriptor_0c843d59d2d938e7) }

var fileDescriptor_0c843d59d2d938e7 = []byte{
	// 264 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0xb1, 0x4a, 0xc4, 0x40,
	0x10, 0x86, 0x5d, 0xa3, 0x97, 0xbb, 0x41, 0x11, 0x16, 0x4f, 0xd7, 0x13, 0x34, 0xa4, 0x4a, 0x95,
	0x42, 0x1f, 0x21, 0x85, 0xd8, 0x58, 0x2c, 0x82, 0x65, 0x48, 0xb2, 0x43, 0xc8, 0xc9, 0x66, 0xe2,
	0x65, 0x02, 0x36, 0xbe, 0x96, 0xcf, 0x27, 0x1b, 0x72, 0x78, 0x09, 0xd1, 0x6e, 0x7f, 0x66, 0x67,
	0xbe, 0x6f, 0x06, 0xa0, 0x26, 0x83, 0x71, 0xb3, 0x23, 0x26, 0xb9, 0x2c, 0xbb, 0xac, 0x7f, 0x85,
	0x5f, 0x70, 0xa9, 0xd1, 0x12, 0x63, 0x42, 0xd6, 0x66, 0xb5, 0xd1, 0xf8, 0xd1, 0x61, 0xcb, 0xf2,
	0x06, 0x96, 0xf8, 0x89, 0x45, 0x5a, 0x58, 0xa3, 0x44, 0x20, 0xa2, 0x33, 0xed, 0xbb, 0x9c, 0x58,
	0x23, 0xd7, 0xb0, 0xd8, 0x52, 0x9e, 0x56, 0x46, 0x1d, 0x07, 0x22, 0x5a, 0xe9, 0xd3, 0x2d, 0xe5,
	0xcf, 0x46, 0x2a, 0xf0, 0xb9, 0xb2, 0x48, 0x1d, 0x2b, 0x2f, 0x10, 0x91, 0xa7, 0xf7, 0xd1, 0xcd,
	0x22, 0x6e, 0xd2, 0x82, 0x0c, 0xaa, 0x93, 0xbe, 0xc5, 0x27, 0x6e, 0x12, 0x32, 0x18, 0x5e, 0xc3,
	0x7a, 0x82, 0x6f, 0x1b, 0xaa, 0x5b, 0x0c, 0x4b, 0xb8, 0xd2, 0x58, 0x56, 0x2d, 0xe3, 0x6e, 0x62,
	0xf6, 0x8b, 0x17, 0x87, 0xf8, 0x5b, 0x58, 0x39, 0x08, 0xd3, 0x3b, 0xd6, 0x83, 0x98, 0xa3, 0xbe,
	0xba, 0x3c, 0x32, 0xf0, 0xc6, 0x06, 0x6a, 0x06, 0xd4, 0x2b, 0x3c, 0x7c, 0x0b, 0xf0, 0x9f, 0xba,
	0xec, 0x85, 0x0c, 0x4a, 0x0d, 0xe7, 0x23, 0x4f, 0x79, 0x17, 0xef, 0x4f, 0x18, 0xcf, 0xdd, 0x6f,
	0x73, 0xff, 0x67, 0x7d, 0x58, 0xf0, 0x48, 0xbe, 0xc1, 0xc5, 0x84, 0x2c, 0x83, 0xc3, 0xae, 0xb9,
	0xed, 0x37, 0xff, 0xfd, 0x18, 0x06, 0xe7, 0x8b, 0xbe, 0xfe, 0xf8, 0x13, 0x00, 0x00, 0xff, 0xff,
	0x8a, 0x9d, 0xa2, 0xbe, 0xf2, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GuaNodeClient is the client API for GuaNode service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GuaNodeClient interface {
	RemoteCommand(ctx context.Context, in *RemoteCommandRequest, opts ...grpc.CallOption) (*RemoteCommandResponse, error)
	RegisterCommand(ctx context.Context, in *RegisterCommandRequest, opts ...grpc.CallOption) (*RegisterCommandReponse, error)
}

type guaNodeClient struct {
	cc *grpc.ClientConn
}

func NewGuaNodeClient(cc *grpc.ClientConn) GuaNodeClient {
	return &guaNodeClient{cc}
}

func (c *guaNodeClient) RemoteCommand(ctx context.Context, in *RemoteCommandRequest, opts ...grpc.CallOption) (*RemoteCommandResponse, error) {
	out := new(RemoteCommandResponse)
	err := c.cc.Invoke(ctx, "/guaproto.GuaNode/RemoteCommand", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guaNodeClient) RegisterCommand(ctx context.Context, in *RegisterCommandRequest, opts ...grpc.CallOption) (*RegisterCommandReponse, error) {
	out := new(RegisterCommandReponse)
	err := c.cc.Invoke(ctx, "/guaproto.GuaNode/RegisterCommand", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GuaNodeServer is the server API for GuaNode service.
type GuaNodeServer interface {
	RemoteCommand(context.Context, *RemoteCommandRequest) (*RemoteCommandResponse, error)
	RegisterCommand(context.Context, *RegisterCommandRequest) (*RegisterCommandReponse, error)
}

func RegisterGuaNodeServer(s *grpc.Server, srv GuaNodeServer) {
	s.RegisterService(&_GuaNode_serviceDesc, srv)
}

func _GuaNode_RemoteCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoteCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuaNodeServer).RemoteCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/guaproto.GuaNode/RemoteCommand",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuaNodeServer).RemoteCommand(ctx, req.(*RemoteCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuaNode_RegisterCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuaNodeServer).RegisterCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/guaproto.GuaNode/RegisterCommand",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuaNodeServer).RegisterCommand(ctx, req.(*RegisterCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GuaNode_serviceDesc = grpc.ServiceDesc{
	ServiceName: "guaproto.GuaNode",
	HandlerType: (*GuaNodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RemoteCommand",
			Handler:    _GuaNode_RemoteCommand_Handler,
		},
		{
			MethodName: "RegisterCommand",
			Handler:    _GuaNode_RegisterCommand_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "node.proto",
}
